### ISSUE TITLE
cosine, sine and exp functions

### ISSUE THREAD

**Issue by sisirajaya** [edwig/BCD#1]
afp versions of these functions evaluated at 0.0 goes into an infinite loop.

numeric::PI needs precision and scale arguments.

**Comment by edwig** [comment]
Hi Sisirajaya,

 

Thanks for the issues. Just commited the fixes on github/Edwig/bcd

 

Best regards,

Edwig Huisman

 

Van: sisirajaya <notifications@github.com> 
Verzonden: maandag 2 maart 2020 18:48
Aan: edwig/BCD <BCD@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [edwig/BCD] cosine, sine and exp functions (#1)

 

These functions evaluated at 0.0 goes into an infinite loop.
