### ISSUE TITLE
0.0 is not handled correctly boolean <

### ISSUE THREAD

**Issue by sisirajaya** [edwig/BCD#2]
When the Taylor series is evaluated for functions such as sine arcsine tan arcTan the comparison to epsilon does not get evaluated correctly when number is 0.0 in bcd . Therefore, it goes into a infinite loop.

     if (between.AbsoluteValue() < epsilon)
      {
         break;
      }

**Comment by edwig** [comment]
Hi Sisirajaya,

 

Just commited the fix.

 

Edwig

 

Van: sisirajaya <notifications@github.com> 
Verzonden: dinsdag 3 maart 2020 17:45
Aan: edwig/BCD <BCD@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [edwig/BCD] 0.0 is not handled correctly boolean < (#2)

 

When the Taylor series is evaluated for functions such as sine arcsine tan arcTan the comparison to epsilon does not get evaluated correctly when number is 0.0 in bcd . Therefore, it goes into a infinite loop.

 if (between.AbsoluteValue() < epsilon)
  {
     break;
  }

**Comment by sisirajaya** [comment]
Thank you I will download and try it. I just had it to return 0 if the number is 0.0

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
