### ISSUE TITLE
std::string  _afp_ftoa function returns wrong string

### ISSUE THREAD

**Issue by sisirajaya** [edwig/BCD#8]
when afp object casted to double you get wrong value;

   afp af = 30.0;
   double daf = (double)af;

now daf is 3.0

Fix:

in afp.cpp lines 2159 should be:
      // erase "." only if it is there
      if (s[2]=='.')
         s.erase(2,1);

**Comment by edwig** [comment]
Corrected and added UnitTestAFP to test it. See T001_double.
